#include <allegro5/allegro.h>

int get_type(ALLEGRO_EVENT);
ALLEGRO_ANY_EVENT get_any(ALLEGRO_EVENT);
ALLEGRO_DISPLAY_EVENT get_display(ALLEGRO_EVENT);
ALLEGRO_JOYSTICK_EVENT get_joystick(ALLEGRO_EVENT);
ALLEGRO_KEYBOARD_EVENT get_keyboard(ALLEGRO_EVENT);
ALLEGRO_MOUSE_EVENT get_mouse(ALLEGRO_EVENT);
ALLEGRO_TIMER_EVENT get_timer(ALLEGRO_EVENT);
